In [ ]:
#1.相片近來
#2.偵測果樹範圍
#3.有了範圍的roi之後，每一張再用一個for迴圈把每一棵樹取出來，並判斷
#4.判斷的那棵樹如果有問題，就框起來
#5.框起來之後將文字放到圖上

In [1]:
#所有需要import的東西都放到這裡
import warnings
warnings.filterwarnings('ignore')
import os
import sys
import random
import math
import numpy as np
import skimage.io
import matplotlib.pyplot as plt
plt.switch_backend('agg')
import cv2
import time
import mrcnn.model as modellib
import threading
import tkinter as tk
import exifread
import socket
import PIL
import tkintermapview
import piexif
import io
import requests
import webbrowser
import tensorflow as tf
from piexif import dump
from djitellopy import tello
from PIL import Image
from PIL import ImageTk
from tkinter import Label,Button,PhotoImage,Text,Listbox,Scrollbar,Canvas
from tkinter import filedialog
from tkinter import messagebox
from keras.preprocessing import image
from tensorflow import keras
from mrcnn.config import Config
from datetime import datetime
from mrcnn import utils,visualize
from keras import backend as K
from tkinterdnd2 import DND_FILES,DND_TEXT, TkinterDnD
from tensorflow.python.keras.backend import set_session

Using TensorFlow backend.


In [ ]:
def MaskTree(image): #圖片近來之後就圈樹，並return一組roi陣列數據，近來可能必須包含圖片路徑，model
    ROOT_DIR = os.getcwd()
    sys.path.append(ROOT_DIR)  # To find local version of the library
    MODEL_DIR = os.path.join(ROOT_DIR, "logs")
    COCO_MODEL_PATH = os.path.join(MODEL_DIR ,"mask_rcnn_shapes_0001.h5")
    
    if not os.path.exists(COCO_MODEL_PATH):
        utils.download_trained_weights(COCO_MODEL_PATH)
        print("cuiwei***********************")

    IMAGE_DIR = os.path.join(ROOT_DIR, "images")

    class ShapesConfig(Config): #這個class與下面那個class可以在開始前就執行
        NAME = "shapes"
        GPU_COUNT = 1
        IMAGES_PER_GPU = 1
        NUM_CLASSES = 1 + 1
        IMAGE_MIN_DIM = 256
        IMAGE_MAX_DIM = 384
        RPN_ANCHOR_SCALES = (8 * 6, 16 * 6, 32 * 6, 64 * 6, 128 * 6)
        TRAIN_ROIS_PER_IMAGE =100
        STEPS_PER_EPOCH = 100
        VALIDATION_STEPS = 50

    class InferenceConfig(ShapesConfig):
        GPU_COUNT = 1
        IMAGES_PER_GPU = 1

    config = InferenceConfig()

    model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config) #model可以一開始就load好，省時間，判斷快速
    model.load_weights(COCO_MODEL_PATH, by_name=True)
    #class_names = ['BG', 'tree'] #到時候不需要這一行
    image = cv2.imread("./images/myimg.jpg") #到時候這句要註銷，判斷的圖片變成
    a=datetime.now()
    results = model.detect([image], verbose=1)
    b=datetime.now()
    print("時間",(b-a).seconds)
    r = results[0]
    #visualize.display_instances(image, r['rois'], r['masks'], r['class_ids'],class_names, r['scores']) #到時候不用顯示出來

#def JudgeTree(image): #傳入切好的圖片，判斷完之後回傳結果，如果weak就在本來的圖片上標註不健康
model = keras.models.load_model(r'C:\Users\LAI\fiveisbest\saved-model-06.h5') #可以preload好
#到時候自己拆
img1=cv2.imread(r"C:\Users\LAI\trees\health\RGB\RGB_001.jpg")
img1=cv2.resize(img1,(600,600))
img2=cv2.imread(r"C:\Users\LAI\trees\health\R\R_001.jpg",cv2.IMREAD_GRAYSCALE)
img2=cv2.resize(img2,(600,600))
img3=cv2.imread(r"C:\Users\LAI\trees\health\G\G_001.jpg",cv2.IMREAD_GRAYSCALE)
img3=cv2.resize(img3,(600,600))
img4=cv2.imread(r"C:\Users\LAI\trees\health\B\B_001.jpg",cv2.IMREAD_GRAYSCALE)
img4=cv2.resize(img4,(600,600))

img1=np.array(img1, dtype='float')
img2=np.array(img2, dtype='float')
img3=np.array(img3, dtype='float')
img4=np.array(img4, dtype='float')

img1=np.expand_dims(img1, axis=0)
img2=np.expand_dims(img2, axis=0)
img3=np.expand_dims(img3, axis=0)
img4=np.expand_dims(img4, axis=0)
img2=np.expand_dims(img2, axis=3)
img3=np.expand_dims(img3, axis=3)
img4=np.expand_dims(img4, axis=3)

img1/=255
img2/=255
img3/=255
img4/=255

rslt= model.predict([img1,img2,img3,img4])

print(rslt)
if (rslt[0][0]>rslt[0][1]):
    prediction="health"
else:
    prediction="weak"
print(prediction)

In [ ]:
import warnings
warnings.filterwarnings('ignore')
#MaskRCNN preload start
print('Start Loading MaskRCNN Model...')
a=datetime.now()
ROOT_DIR = os.getcwd()
sys.path.append(ROOT_DIR)  # To find local version of the library
MODEL_DIR = os.path.join(ROOT_DIR, "logs")
COCO_MODEL_PATH = os.path.join(MODEL_DIR ,"mask_rcnn_shapes_0001.h5")
if not os.path.exists(COCO_MODEL_PATH):
    utils.download_trained_weights(COCO_MODEL_PATH)
    print("cuiwei***********************")
IMAGE_DIR = os.path.join(ROOT_DIR, "images")
class ShapesConfig(Config): #這個class與下面那個class可以在開始前就執行
    NAME = "shapes"
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
    NUM_CLASSES = 1 + 1
    IMAGE_MIN_DIM = 256
    IMAGE_MAX_DIM = 384
    RPN_ANCHOR_SCALES = (8 * 6, 16 * 6, 32 * 6, 64 * 6, 128 * 6)
    TRAIN_ROIS_PER_IMAGE =100
    STEPS_PER_EPOCH = 100
    VALIDATION_STEPS = 50
class InferenceConfig(ShapesConfig):
    GPU_COUNT = 1
    IMAGES_PER_GPU = 1
config = InferenceConfig()
rcnn_model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config) #model可以一開始就load好，省時間，判斷快速
rcnn_model.load_weights(COCO_MODEL_PATH, by_name=True)
print('End Loading MaskRCNN Model...')
b=datetime.now()
print("Loading MaskRCNN Model Time:",(b-a).seconds)
#MaskRCNN preload end

#CNN preload start
a=datetime.now()
print('Start Loading CNN Model...')
cnn_model = keras.models.load_model(r'C:\Users\LAI\fiveisbest\saved-model-06.h5')
print('End Loading CNN Model...')
b=datetime.now()
print("Loadin CNN Model Time:",(b-a).seconds)
#CNN preload end

def MaskRCNN(image):
    a=datetime.now()
    results = rcnn_model.detect([image], verbose=1)
    b=datetime.now()
    print("Detect Time:",(b-a).seconds)
    r=results[0]
    display_image = image
    for i in range(0,int(r['rois'].size/4)):
        small_tree = np.array_split(r['rois'][i],[1,2,3,4])
        print(r['rois'][i])
        tree = image[int(small_tree[0]):int(small_tree[2]), int(small_tree[1]):int(small_tree[3])]
        ishealth=CNN(tree)
        if ishealth:
            continue
        else:
            cv2.rectangle(display_image, (int(small_tree[1]), int(small_tree[0])), (int(small_tree[3]), int(small_tree[2])), (0,0,255), 4, cv2.LINE_AA)
    
def CNN(myimage): #這是小圖片，要自己拆
    RGB = cv2.resize(myimage,(600,600))
    (B, G, R) = cv2.split(RGB)
    RGB=np.array(RGB, dtype='float')
    R=np.array(R, dtype='float')
    G=np.array(G, dtype='float')
    B=np.array(B, dtype='float')
    RGB=np.expand_dims(RGB, axis=0)
    R=np.expand_dims(R, axis=0)
    G=np.expand_dims(G, axis=0)
    B=np.expand_dims(B, axis=0)
    R=np.expand_dims(R, axis=3)
    G=np.expand_dims(G, axis=3)
    B=np.expand_dims(B, axis=3)
    RGB/=255
    R/=255
    G/=255
    B/=255
    a=datetime.now()
    rslt= cnn_model.predict([RGB,R,G,B])
    b=datetime.now()
    print("Detect Time:",(b-a).seconds)
    print(rslt)
    if (rslt[0][0]>rslt[0][1]):
        return True#prediction="health"
    else:
        plt.imshow(myimage)
        plt.show()
        return False
    
tree_image = cv2.imread("./images/myimg.jpg")
MaskRCNN(tree_image)

In [2]:
def create_main_window():
    window_main=tk.Toplevel(background='#C5E0B4')
    window_main.title('怎麼柚識你-果樹黃化預警系統')
    w = window_main.winfo_screenwidth()
    h = window_main.winfo_screenheight()
    window_main.geometry("%dx%d" %(w, h))
    window_main.state("zoomed")

    pic_size=0.8
    pic1_path = os.path.join(os.getcwd(), "systempic", "homepage", "pic_analyze_button.png") #分析圖片按鈕
    pic1 = Image.open(pic1_path)
    pic1 = pic1.resize((int(pic1.size[0]*pic_size), int(pic1.size[1]*pic_size)))
    pic1_tk = ImageTk.PhotoImage(image=pic1)
    button_analyze = Canvas(window_main, bg="#C5E0B4", width=pic1.size[0], height=pic1.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_analyze.bind("<Button-1>", lambda e: create_analyze_window())
    button_analyze.place(x=125,y=670)
    button_analyze.create_image(0,0,anchor=tk.NW,image=pic1_tk)
    
    pic2_path = os.path.join(os.getcwd(), "systempic", "homepage", "fly_analyze_button.png") #空拍機按鈕
    pic2 = Image.open(pic2_path)
    pic2 = pic2.resize((int(pic2.size[0]*pic_size), int(pic2.size[1]*pic_size)))
    pic2_tk = ImageTk.PhotoImage(image=pic2)
    button_fly = Canvas(window_main, bg="#C5E0B4", width=pic2.size[0], height=pic2.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_fly.bind("<Button-1>", lambda e: create_fly_window())
    button_fly.place(x=635,y=670)
    button_fly.create_image(0,0,anchor=tk.NW,image=pic2_tk)
    
    pic3_path = os.path.join(os.getcwd(), "systempic", "homepage", "search_button.png") #地理位置按鈕
    pic3 = Image.open(pic3_path)
    pic3 = pic3.resize((int(pic3.size[0]*pic_size), int(pic3.size[1]*pic_size)))
    pic3_tk = ImageTk.PhotoImage(image=pic3)
    button_geo = Canvas(window_main, bg="#C5E0B4", width=pic3.size[0], height=pic3.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_geo.bind("<Button-1>", lambda e: geo_window())
    button_geo.place(x=1145,y=670)
    button_geo.create_image(0,0,anchor=tk.NW,image=pic3_tk)
    
    pic4_path = os.path.join(os.getcwd(), "systempic", "homepage", "pic_analyze.png") #圖片分析圖片
    pic4 = Image.open(pic4_path)
    pic4 = pic4.resize((int(pic4.size[0]*pic_size), int(pic4.size[1]*pic_size)))
    pic4_tk = ImageTk.PhotoImage(image=pic4)
    pic_analyze = Canvas(window_main, bg="#C5E0B4", width=pic4.size[0], height=pic4.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    pic_analyze.bind("<Button-1>", lambda e: create_analyze_window())
    pic_analyze.place(x=85,y=280)
    pic_analyze.create_image(0,0,anchor=tk.NW,image=pic4_tk)
    
    pic5_path = os.path.join(os.getcwd(), "systempic", "homepage", "fly_analyze.png") #空拍機按鈕
    pic5 = Image.open(pic5_path)
    pic5 = pic5.resize((int(pic5.size[0]*pic_size), int(pic5.size[1]*pic_size)))
    pic5_tk = ImageTk.PhotoImage(image=pic5)
    pic_fly = Canvas(window_main, bg="#C5E0B4", width=pic5.size[0], height=pic5.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    pic_fly.bind("<Button-1>", lambda e: create_fly_window())
    pic_fly.place(x=595,y=280)
    pic_fly.create_image(0,0,anchor=tk.NW,image=pic5_tk)
    
    pic6_path = os.path.join(os.getcwd(), "systempic", "homepage", "search.png") #地理位置按鈕
    pic6 = Image.open(pic6_path)
    pic6 = pic6.resize((int(pic6.size[0]*pic_size), int(pic6.size[1]*pic_size)))
    pic6_tk = ImageTk.PhotoImage(image=pic6)
    pic_geo = Canvas(window_main, bg="#C5E0B4", width=pic6.size[0], height=pic6.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    pic_geo.bind("<Button-1>", lambda e: geo_window())
    pic_geo.place(x=1105,y=280)
    pic_geo.create_image(0,0,anchor=tk.NW,image=pic6_tk)
    
    pic7_path = os.path.join(os.getcwd(), "systempic", "homepage", "title.png") #標題圖
    pic7 = Image.open(pic7_path)
    pic7 = pic7.resize((int(pic7.size[0]*0.7), int(pic7.size[1]*0.7)))
    pic7_tk = ImageTk.PhotoImage(image=pic7)
    canvas = Canvas(window_main, bg="#C5E0B4", width=pic7.size[0], height=pic7.size[1], bd=0, highlightthickness=0, relief='ridge')
    canvas.place(x=300,y=20)
    canvas.create_image(0,0,anchor=tk.NW,image=pic7_tk)
    
    def on_closing():
        if messagebox.askokcancel("Quit", "Do you want to quit?"):
            window_main.destroy()
            root.destroy()
    window_main.protocol("WM_DELETE_WINDOW", on_closing)
    window_main.mainloop()
    
def create_analyze_window():
    imgname=[] #紀錄圖片完整路徑
    def open_weakfolder():
        try:
            os.system('start '+weakfolderpath)
        except:
            T.insert(tk.END,"找不到路徑！\n")
            T.see(tk.END)
    def AnalyzeProcess():
        threading.Thread(target=LoadModel).start()
    def LoadModel():
        def write_gps(thisimg_path,path):
            gps_ifd = piexif.load(thisimg_path)
            exif_bytes = piexif.dump(gps_ifd)
            piexif.insert(exif_bytes, path)
        def MaskRCNN(image,img_name,weakfolder,thisimg_path):
            results = rcnn_model.detect([image], verbose=1)
            r=results[0]
            display_image = image
            for i in range(0,int(r['rois'].size/4)):
                small_tree = np.array_split(r['rois'][i],[1,2,3,4])
                print(r['rois'][i])
                tree = image[int(small_tree[0]):int(small_tree[2]), int(small_tree[1]):int(small_tree[3])]
                ishealth=CNN(tree)
                if ishealth:
                    cv2.rectangle(display_image, (int(small_tree[1]), int(small_tree[0])), (int(small_tree[3]), int(small_tree[2])), (0,255,0), 8, cv2.LINE_AA)
                else:
                    cv2.rectangle(display_image, (int(small_tree[1]), int(small_tree[0])), (int(small_tree[3]), int(small_tree[2])), (0,0,255), 8, cv2.LINE_AA)

            dirs=os.path.join(os.getcwd() ,"DetectImage",str(weakfolder))
            if not os.path.exists(dirs):
                os.makedirs(dirs)
            path = os.path.join(dirs,img_name) #path是圖片的路徑
            imgname.append(path)
            mylist.insert(tk.END,img_name)
            cv2.imwrite(path, display_image)
            write_gps(thisimg_path,path)     
        def CNN(myimage): #這是小圖片，要自己拆
            RGB = cv2.resize(myimage,(600,600))
            (B, G, R) = cv2.split(RGB)
            RGB=np.array(RGB, dtype='float')
            R=np.array(R, dtype='float')
            G=np.array(G, dtype='float')
            B=np.array(B, dtype='float')
            RGB=np.expand_dims(RGB, axis=0)
            R=np.expand_dims(R, axis=0)
            G=np.expand_dims(G, axis=0)
            B=np.expand_dims(B, axis=0)
            R=np.expand_dims(R, axis=3)
            G=np.expand_dims(G, axis=3)
            B=np.expand_dims(B, axis=3)
            RGB/=255
            R/=255
            G/=255
            B/=255
            rslt= cnn_model.predict([RGB,R,G,B])
            if (rslt[0][0]>rslt[0][1]):
                return True
            else:
                return False
            
        analyze_folder_path=folder_path.cget("text") #取得想分析圖檔路徑
        try:
            i=0
            for img in os.listdir(analyze_folder_path):
                i=i+1
        except:
            T.insert(tk.END,"找不到該路徑！\n")
            T.see(tk.END)
            return
        K.clear_session()
        T.insert(tk.END,'下載模型中...\n')
        T.see(tk.END)
        ROOT_DIR = os.getcwd()
        sys.path.append(ROOT_DIR)  # To find local version of the library
        MODEL_DIR = os.path.join(ROOT_DIR, "logs")
        COCO_MODEL_PATH = os.path.join(MODEL_DIR ,"mask_rcnn_shapes_0010.h5")
        if not os.path.exists(COCO_MODEL_PATH):
            utils.download_trained_weights(COCO_MODEL_PATH)
            print("cuiwei***********************")
        class ShapesConfig(Config): #這個class與下面那個class可以在開始前就執行
            NAME = "shapes"
            GPU_COUNT = 1
            IMAGES_PER_GPU = 1
            NUM_CLASSES = 1 + 1
            IMAGE_MIN_DIM = 256
            IMAGE_MAX_DIM = 384
            RPN_ANCHOR_SCALES = (8 * 6, 16 * 6, 32 * 6, 64 * 6, 128 * 6)
            TRAIN_ROIS_PER_IMAGE =100
            STEPS_PER_EPOCH = 100
            VALIDATION_STEPS = 50
        class InferenceConfig(ShapesConfig):
            GPU_COUNT = 1
            IMAGES_PER_GPU = 1
        config = InferenceConfig()
        rcnn_model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config) #model可以一開始就load好，省時間，判斷快速
        rcnn_model.load_weights(COCO_MODEL_PATH, by_name=True)
        #MaskRCNN preload end

        #CNN preload start
        cnn_model_dir=os.path.join(os.getcwd() ,"fiveisbest","saved-model-06.h5")
        cnn_model = keras.models.load_model(cnn_model_dir)
        T.insert(tk.END,'模型下載完成！\n')
        T.see(tk.END)
        #CNN preload end
        
        #load Image
        T.insert(tk.END,"下載圖片中...\n")
        T.see(tk.END)
        img_data=[]
        for img in os.listdir(analyze_folder_path):
            img_path=analyze_folder_path+"/"+img
            img_arr=cv2.imread(img_path)
            img_data.append([img_arr,img])
            
        T.insert(tk.END,"圖片下載完成！\n")
        T.see(tk.END)
        T.insert(tk.END,"待分析圖片張數："+str(len(img_data))+" 張\n")
        T.see(tk.END)
        
        #start analyze
        weakfolder=datetime.now().strftime('%Y%m%d%H%M%S')
        global weakfolderpath
        weakfolderpath=os.path.join(os.getcwd() ,"DetectImage",str(weakfolder))
        for i in range(0,len(img_data)):
            T.insert(tk.END,"圖片 "+img_data[i][1]+" 分析中...\n")
            T.see(tk.END)
            thisimg_path=os.path.join(analyze_folder_path,img_data[i][1])
            MaskRCNN(img_data[i][0],img_data[i][1],weakfolder,thisimg_path)
        
        T.insert(tk.END,"分析結束！\n")
        pic_dirs=os.path.join(os.getcwd() ,"DetectImage")
        T.insert(tk.END,"分析結果儲存於 "+str(weakfolderpath)+"\n")
        T.see(tk.END)
        
    root.destroy()
    window_analyze = TkinterDnD.Tk()
    window_analyze.title('分析圖片')
    window_analyze.configure(bg='#C5E0B4') 
    
    def select_folder():
        select_folder = tk.Tk()
        select_folder.destroy()
        file_path = filedialog.askdirectory()
        folder_path.config(text=file_path)
    
    w = window_analyze.winfo_screenwidth()
    h = window_analyze.winfo_screenheight()
    window_analyze.geometry("%dx%d" %(w, h))
    window_analyze.state("zoomed")
    
    pic_size=0.6
    
    pic1_path = os.path.join(os.getcwd(), "systempic", "analyze", "select_folder.png") #分析圖片按鈕
    pic1 = Image.open(pic1_path)
    pic1 = pic1.resize((int(pic1.size[0]*pic_size), int(pic1.size[1]*pic_size)))
    pic1_tk = ImageTk.PhotoImage(image=pic1)
    button_select = Canvas(window_analyze, bg="#C5E0B4", width=pic1.size[0], height=pic1.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_select.bind("<Button-1>", lambda e: select_folder())
    button_select.place(x=20,y=25)
    button_select.create_image(0,0,anchor=tk.NW,image=pic1_tk)
    
    pic2_path = os.path.join(os.getcwd(), "systempic", "analyze", "start_analyze.png") #分析圖片按鈕
    pic2 = Image.open(pic2_path)
    pic2 = pic2.resize((int(pic2.size[0]*pic_size), int(pic2.size[1]*pic_size)))
    pic2_tk = ImageTk.PhotoImage(image=pic2)
    button_analyze = Canvas(window_analyze, bg="#C5E0B4", width=pic2.size[0], height=pic2.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_analyze.bind("<Button-1>", lambda e: AnalyzeProcess())
    button_analyze.place(x=1350,y=25)
    button_analyze.create_image(0,0,anchor=tk.NW,image=pic2_tk)
    
    pic3_path = os.path.join(os.getcwd(), "systempic", "analyze", "folder_path.png") #分析圖片按鈕
    pic3 = Image.open(pic3_path)
    pic3 = pic3.resize((int(pic3.size[0]*pic_size), int(pic3.size[1]*pic_size)))
    pic3_tk = ImageTk.PhotoImage(image=pic3)
    button_analyze = Canvas(window_analyze, bg="#C5E0B4", width=pic3.size[0], height=pic3.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_analyze.place(x=285,y=25)
    button_analyze.create_image(0,0,anchor=tk.NW,image=pic3_tk)
    
    folder_path = Label(window_analyze,text="", font=("Courier", 18, "italic"), bg='white')
    folder_path.place(x=495,y=49)
    
    text_frame = tk.Frame(window_analyze,height=150,width=840)
    text_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    T = Text(text_frame, height=150, width=840, bg="white", font="Calibri 14 bold")
    T.pack()
    text_frame.place(x=35, y=140)
    
    display_img_after_frame = tk.Frame(window_analyze,width=600,height=400,bg="white") ####解析後圖片放的地方
    display_img_after_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    display_img_after_frame.place(x=271,y=310)
    display_img_after=Label(display_img_after_frame,bg="white",text="解析後照片", font="Courier 18 bold",width=800,height=533)#解析後照片
    display_img_after.pack()
    
    def onselect(event):
        def get_img():
            try:
                file_name=""
                for item in mylist.curselection():
                    file_name=str(imgname[item])
                display_pic = cv2.imread(file_name)
                display_pic = cv2.cvtColor(display_pic, cv2.COLOR_BGR2RGB)
                display_pic = cv2.resize(display_pic, (600, 450), interpolation=cv2.INTER_AREA)
                im = Image.fromarray(display_pic)
                imgtk2 = ImageTk.PhotoImage(image=im)
                display_img_after.config(image=imgtk2)
                display_img_after.image = imgtk2
            except:
                pass
        threading.Thread(target=get_img).start()
    out_list_frame = tk.Frame(window_analyze,width=190,height=480,bg="yellow")
    list_frame = tk.Frame(out_list_frame,width=190,height=480,bg="green") #####圖片名稱列表
    list_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    mylist=tk.Listbox(list_frame,font="Calibri 14 bold",width=190,height=480)
    mylist.pack(side="left",fill="both",expand=1)
    scrollbar = tk.Scrollbar(out_list_frame)
    scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
    scrollbar.config(command=mylist.yview)
    out_list_frame.place(x=35,y=310)
    list_frame.pack(expand=1, fill="both", side="left")
    mylist.bind('<<ListboxSelect>>', onselect)
    
    global google_map_url
    google_map_url=""
    def drop_file(event): #做超連結連結到google map
        def _get_if_exist(data, key):
            if key in data:
                return data[key]
            return None
        def _convert_to_degress(value):
            d = float(value.values[0].num) / float(value.values[0].den)
            m = float(value.values[1].num) / float(value.values[1].den)
            s = float(value.values[2].num) / float(value.values[2].den)
            return d + (m / 60.0) + (s / 3600.0)
        def get_exif_location(exif_data):
            lat = None
            lon = None
            gps_latitude = _get_if_exist(exif_data, 'GPS GPSLatitude')
            gps_latitude_ref = _get_if_exist(exif_data, 'GPS GPSLatitudeRef')
            gps_longitude = _get_if_exist(exif_data, 'GPS GPSLongitude')
            gps_longitude_ref = _get_if_exist(exif_data, 'GPS GPSLongitudeRef')
            if gps_latitude and gps_latitude_ref and gps_longitude and gps_longitude_ref:
                lat = _convert_to_degress(gps_latitude)
                if gps_latitude_ref.values[0] != 'N':
                    lat = 0 - lat
                lon = _convert_to_degress(gps_longitude)
                if gps_longitude_ref.values[0] != 'E':
                    lon = 0 - lon
            return lat, lon
        tags = exifread.process_file(open(event.data, 'rb'))
        geo = {i:tags[i] for i in tags.keys() if i.startswith('GPS')}
        lat,lon=get_exif_location(geo)
        api_key='AIzaSyDU0ez136Zk81khQv2Gx4N5_2ZI_lUism0'
        url = "https://maps.googleapis.com/maps/api/staticmap?key="+api_key+"&center="+str(lat)+","+str(lon)+"&zoom=20&maptype=satellite&size=640x640&format=jpg&markers=color:red%7Clabel:拍攝地點%7C"+str(lat)+","+str(lon)
        ret = requests.get(url).content
        im = Image.open(io.BytesIO(ret))
        imgtk2 = ImageTk.PhotoImage(image=im)
        mymap.config(image=imgtk2)
        mymap.image = imgtk2
        google_map_url="https://www.google.com/maps/search/?api=1&query="+str(lat)+" "+str(lon)+"&basemap=satellite"
    def google_map():
        def _get_if_exist(data, key):
            if key in data:
                return data[key]
            return None
        def _convert_to_degress(value):
            d = float(value.values[0].num) / float(value.values[0].den)
            m = float(value.values[1].num) / float(value.values[1].den)
            s = float(value.values[2].num) / float(value.values[2].den)
            return d + (m / 60.0) + (s / 3600.0)
        def get_exif_location(exif_data):
            lat = None
            lon = None
            gps_latitude = _get_if_exist(exif_data, 'GPS GPSLatitude')
            gps_latitude_ref = _get_if_exist(exif_data, 'GPS GPSLatitudeRef')
            gps_longitude = _get_if_exist(exif_data, 'GPS GPSLongitude')
            gps_longitude_ref = _get_if_exist(exif_data, 'GPS GPSLongitudeRef')
            if gps_latitude and gps_latitude_ref and gps_longitude and gps_longitude_ref:
                lat = _convert_to_degress(gps_latitude)
                if gps_latitude_ref.values[0] != 'N':
                    lat = 0 - lat
                lon = _convert_to_degress(gps_longitude)
                if gps_longitude_ref.values[0] != 'E':
                    lon = 0 - lon
            return lat, lon
        def get_google_map():
            file_name=""
            for item in mylist.curselection():
                file_name=str(imgname[item])
            tags = exifread.process_file(open(file_name, 'rb'))##
            geo = {i:tags[i] for i in tags.keys() if i.startswith('GPS')}
            lat,lon=get_exif_location(geo)
            api_key='AIzaSyDU0ez136Zk81khQv2Gx4N5_2ZI_lUism0'
            url = "https://maps.googleapis.com/maps/api/staticmap?key="+api_key+"&center="+str(lat)+","+str(lon)+"&zoom=20&maptype=satellite&size=640x640&format=jpg&markers=color:red%7Clabel:拍攝地點%7C"+str(lat)+","+str(lon)
            ret = requests.get(url).content
            im = Image.open(io.BytesIO(ret))
            imgtk2 = ImageTk.PhotoImage(image=im)
            mymap.config(image=imgtk2)
            mymap.image = imgtk2
            global google_map_url
            google_map_url="https://www.google.com/maps/search/?api=1&query="+str(lat)+" "+str(lon)+"&basemap=satellite"
        threading.Thread(target=get_google_map).start()
    def link_to_map(url):
        if (url==None):
            return
        webbrowser.open(url,new=2)
    pic4_path = os.path.join(os.getcwd(), "systempic", "analyze", "put_geo.png") #分析圖片按鈕
    pic4 = Image.open(pic4_path)
    pic4 = pic4.resize((int(pic4.size[0]*pic_size), int(pic4.size[1]*pic_size)))
    pic4_tk = ImageTk.PhotoImage(image=pic4)
    button_map = Canvas(window_analyze, bg="#C5E0B4", width=pic4.size[0], height=pic4.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_map.bind("<Button-1>", lambda e: google_map())
    button_map.create_image(0,0,anchor=tk.NW,image=pic4_tk)
    button_map.place(x=665,y=725)
    
    label_frame = tk.Frame(window_analyze,width=640,height=640,bg="white") #####顯示Google map的地方
    label_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    mymap=tk.Label(label_frame,bg="white",fg="black",text="google map顯示處",font="Calibri 18 bold",width=640,height=640,cursor="hand2")
    mymap.pack()
    mymap.bind("<Button-1>", lambda e: link_to_map(google_map_url))
    mymap.drop_target_register(DND_FILES)
    mymap.dnd_bind('<<Drop>>', drop_file)
    label_frame.place(x=920,y=140)
    
    trees_path = os.path.join(os.getcwd(), "systempic", "analyze", "trees.png") #分析圖片按鈕
    trees = Image.open(trees_path)
    trees = trees.resize((int(trees.size[0]*0.35), int(trees.size[1]*0.35)))
    trees_tk = ImageTk.PhotoImage(image=trees)
    trees_pic = Canvas(window_analyze, bg="#C5E0B4", width=trees.size[0], height=trees.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    trees_pic.place(x=271,y=725)
    trees_pic.create_image(0,0,anchor=tk.NW,image=trees_tk)
    
    def on_closing():
        window_analyze.destroy()
        global root
        root=tk.Tk()
        root.withdraw()
        create_main_window()
    window_analyze.protocol("WM_DELETE_WINDOW", on_closing)
    window_analyze.mainloop()

def create_fly_window(): #加上分析
    global check_path #檢查路徑是否存在
    global save_pic_path #儲存圖片路徑
    global ipcam
    global pic_num #圖片編號
    global save_pic_path
    global save_pic_analyze_path
    pic_num=1
    def load_model():
        global fly_rcnn_model
        global fly_cnn_model
        K.clear_session()
        ROOT_DIR = os.getcwd()
        sys.path.append(ROOT_DIR)  # To find local version of the library
        MODEL_DIR = os.path.join(ROOT_DIR, "logs")
        COCO_MODEL_PATH = os.path.join(MODEL_DIR ,"mask_rcnn_shapes_0015.h5")
        if not os.path.exists(COCO_MODEL_PATH):
            utils.download_trained_weights(COCO_MODEL_PATH)
            print("cuiwei***********************")
        class ShapesConfig(Config):
            NAME = "shapes"
            GPU_COUNT = 1
            IMAGES_PER_GPU = 1
            NUM_CLASSES = 1 + 1
            IMAGE_MIN_DIM = 256
            IMAGE_MAX_DIM = 384
            RPN_ANCHOR_SCALES = (8 * 6, 16 * 6, 32 * 6, 64 * 6, 128 * 6)
            TRAIN_ROIS_PER_IMAGE =100
            STEPS_PER_EPOCH = 100
            VALIDATION_STEPS = 50
        class InferenceConfig(ShapesConfig):
            GPU_COUNT = 1
            IMAGES_PER_GPU = 1
        config = InferenceConfig()
        global graph
        global sess
        sess = tf.Session()
        graph = tf.get_default_graph()
        set_session(sess)
        fly_rcnn_model = modellib.MaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
        fly_rcnn_model.load_weights(COCO_MODEL_PATH, by_name=True)
        fly_cnn_model_dir=os.path.join(os.getcwd() ,"fiveisbest","saved-model-06.h5")
        fly_cnn_model = keras.models.load_model(fly_cnn_model_dir)
        print("load is complete")
        
    def analyze_pic(image,save_path,orgin_path): #import model writegps
        def write_gps(thisimg_path,path):
            gps_ifd = piexif.load(thisimg_path)
            exif_bytes = piexif.dump(gps_ifd)
            piexif.insert(exif_bytes, path)
        def MaskRCNN(image,save_path,orgin_path):
            with graph.as_default():
                results = fly_rcnn_model.detect([image], verbose=0)
                r=results[0]
                display_image = image
                for i in range(0,int(r['rois'].size/4)):
                    small_tree = np.array_split(r['rois'][i],[1,2,3,4])
                    tree = image[int(small_tree[0]):int(small_tree[2]), int(small_tree[1]):int(small_tree[3])]
                    ishealth=CNN(tree)
                    if ishealth:
                        cv2.rectangle(display_image, (int(small_tree[1]), int(small_tree[0])), (int(small_tree[3]), int(small_tree[2])), (0,255,0), 8, cv2.LINE_AA)
                    else:
                        cv2.rectangle(display_image, (int(small_tree[1]), int(small_tree[0])), (int(small_tree[3]), int(small_tree[2])), (0,0,255), 8, cv2.LINE_AA)

                cv2.imwrite(save_path, display_image)
                try:
                    write_gps(orgin_path,save_path)
                except:
                    pass
                image = cv2.resize(image, (532, 400), interpolation=cv2.INTER_AREA)
                rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                im = Image.fromarray(rgb)
                imgtk2 = ImageTk.PhotoImage(image=im)
                after_pic.config(image=imgtk2) #改
                after_pic.image = imgtk2
                global save_pic_path
                global save_pic_analyze_path
                if (save_pic_path==None):
                    os.remove(save_pic_analyze_path)
                    save_pic_analyze_path=None
        def CNN(myimage): #這是小圖片，要自己拆
            RGB = cv2.resize(myimage,(600,600))
            (B, G, R) = cv2.split(RGB)
            RGB=np.array(RGB, dtype='float')
            R=np.array(R, dtype='float')
            G=np.array(G, dtype='float')
            B=np.array(B, dtype='float')
            RGB=np.expand_dims(RGB, axis=0)
            R=np.expand_dims(R, axis=0)
            G=np.expand_dims(G, axis=0)
            B=np.expand_dims(B, axis=0)
            R=np.expand_dims(R, axis=3)
            G=np.expand_dims(G, axis=3)
            B=np.expand_dims(B, axis=3)
            RGB/=255
            R/=255
            G/=255
            B/=255
            with graph.as_default():
                global sess
                set_session(sess)
                rslt= fly_cnn_model.predict([RGB,R,G,B])
                if (rslt[0][0]>rslt[0][1]):
                    return True
                else:
                    return False
        MaskRCNN(image,save_path,orgin_path)
            
    def control_tello():
        global pic_path
        global check_path
        global check_analyze_path
        pic_path = datetime.now().strftime('%Y%m%d%H%M%S')
        check_path = os.path.join(os.getcwd(), "pic", pic_path)
        check_analyze_path = os.path.join(os.getcwd(), "pic_analyze", pic_path)
        def capture_pic():
            global ipcam
            global check_path
            global pic_num
            global save_pic_path
            global save_pic_analyze_path
            save_pic_path = os.path.join(os.getcwd(), "pic", pic_path, "pic_"+str(pic_num)+".jpg")
            save_pic_analyze_path = os.path.join(os.getcwd(), "pic_analyze", pic_path, "pic_"+str(pic_num)+".jpg")
            I = ipcam.getframe()
            if not os.path.exists(check_path):
                os.makedirs(check_path)
            cv2.imwrite(save_pic_path,I)
            pic_num=pic_num+1
            #先儲存到電腦再RESIZE
            I = cv2.resize(I, (532, 400), interpolation=cv2.INTER_AREA)
            rgb = cv2.cvtColor(I, cv2.COLOR_BGR2RGB)
            im = Image.fromarray(rgb)
            imgtk2 = ImageTk.PhotoImage(image=im)
            before_pic.config(image=imgtk2) #改
            before_pic.image = imgtk2
            #開始分析
            if not os.path.exists(check_analyze_path):
                os.makedirs(check_analyze_path)
            threading.Thread(target=analyze_pic(I,save_pic_analyze_path,save_pic_path)).start()
            
        tello_address = ('192.168.10.1', 8889)
        local_address = ('', 8890)
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.bind(local_address)
        def send(message):
            try:
                sock.sendto(message.encode(), tello_address)
                print("Sending message: " + message)
            except Exception as e:
                print("Error sending: " + str(e))
        def receive():
            while True:
                try:
                    response, ip_address = sock.recvfrom(128)
                    print("Received message: " + response.decode(encoding='utf-8'))
                except Exception as e:
                    print("Error receiving: " + str(e))
                    break
        receiveThread = threading.Thread(target=receive)  #接收無人機訊息用
        receiveThread.daemon = True
        receiveThread.start()
        control_cam=True  #控制空拍機鏡頭的連接
        #define按鈕功能在這個視窗
        def command():
            send('command')
        def moveforward(x): #x=20~500
            send('forward '+str(x))
        def moveback(x): #x=20~500
            send('back '+str(x))
        def moveleft(x): #x=20~500
            send('left '+str(x))
        def moveright(x): #x=20~500
            send('right '+str(x))
        def moveup(x): #x=20~500
            send('up '+str(x))
        def movedown(x): #x=20~500
            send('down '+str(x))
        def turnleft(x): #x=1~3600
            send('ccw '+str(x))
        def turnright(x): #x=1~3600
            send('cw '+str(x))
        def takeoff():
            send('takeoff')
        def land():
            send('land')
        def streamoff(): #降落時用
            send('streamoff')
        def streamon():
            send('streamon')
        def battery(): #放在while迴圈得知電量
            send('battery?')
        def key_press(event):
            key=event.char
            if (key=="w"):
                moveforward(50)
            elif (key=="a"):
                moveleft(50)
            elif (key=="s"):
                moveback(50)
            elif (key=="d"):
                moveright(50)
            elif (key=="q"):
                turnleft(30)
            elif (key=="e"):
                turnright(30)
            elif (key=="z"):
                moveup(50)
            elif (key=="c"):
                movedown(50)
            elif (key=="o"):
                takeoff()
            elif (key=="p"):
                land()
            elif (key=="m"):
                t1 = threading.Thread(target=capture_pic, daemon=True)
                t1.start()
            elif (key=="n"):
                t1 = threading.Thread(target=del_pic, daemon=True)
                t1.start()
            elif (key=="h"):
                land()
                streamoff()
                control_cam=False
                ipcam.release()
        window_fly.bind('<KeyPress>',key_press)
        
        command()
        streamon()
        video = "udp://@0.0.0.0:11111"
        class ipcamCapture:
            def __init__(self, URL):
                self.Frame = []
                self.status = False
                self.isstop = False
                self.capture = cv2.VideoCapture(URL)

            def start(self):
                print('ipcam started!')
                threading.Thread(target=self.queryframe, daemon=True, args=()).start()

            def stop(self):
                self.isstop = True
                print('ipcam stopped!')

            def getframe(self):
                return self.Frame.copy()

            def queryframe(self):
                while (not self.isstop):
                    self.status, self.Frame = self.capture.read()

                self.capture.release()
        global ipcam
        ipcam = ipcamCapture(video)
        ipcam.start()
        time.sleep(1)
        
        while (control_cam):
            I = ipcam.getframe()
            I = cv2.resize(I, (800, 600), interpolation=cv2.INTER_AREA)
            rgb = cv2.cvtColor(I, cv2.COLOR_BGR2RGB)
            im = Image.fromarray(rgb)
            imgtk2 = ImageTk.PhotoImage(image=im)
            myvideo.config(image=imgtk2)
            myvideo.image = imgtk2
            
    def control():
        t = threading.Thread(target=control_tello)
        t.daemon = True
        t.start()
    
    def cap_pic():#截圖用
        global ipcam
        global check_path
        global pic_num
        global save_pic_path
        global save_pic_analyze_path
        save_pic_path = os.path.join(os.getcwd(), "pic", pic_path, "pic_"+str(pic_num)+".jpg")
        save_pic_analyze_path = os.path.join(os.getcwd(), "pic_analyze", pic_path, "pic_"+str(pic_num)+".jpg")
        I = ipcam.getframe()
        if not os.path.exists(check_path):
            os.makedirs(check_path)
        cv2.imwrite(save_pic_path,I)
        pic_num=pic_num+1
        #先儲存到電腦再RESIZE
        I = cv2.resize(I, (532, 400), interpolation=cv2.INTER_AREA)
        rgb = cv2.cvtColor(I, cv2.COLOR_BGR2RGB)
        im = Image.fromarray(rgb)
        imgtk2 = ImageTk.PhotoImage(image=im)
        before_pic.config(image=imgtk2) #改
        before_pic.image = imgtk2
        #開始分析
        if not os.path.exists(check_analyze_path):
            os.makedirs(check_analyze_path)
        threading.Thread(target=analyze_pic(I,save_pic_analyze_path,save_pic_path)).start()
    
    def del_pic():
        global save_pic_path
        global save_pic_analyze_path
        if (save_pic_path!=None):
            os.remove(save_pic_path)
            try:
                os.remove(save_pic_analyze_path)
            except:
                pass
            save_pic_path=None
        
    window_fly = tk.Toplevel()
    w = window_fly.winfo_screenwidth()
    h = window_fly.winfo_screenheight()
    window_fly.geometry("%dx%d" %(w, h))
    window_fly.state("zoomed")
    window_fly.title('空拍機即時飛行')
    window_fly.configure(bg='#E2F0D9') 
    
    threading.Thread(target=load_model, daemon=True).start()
    
    keyboard_size=0.65
    pic_size=0.7
    
    imgtk = ImageTk.PhotoImage(file="output.png") ##影像呈現地點
    myvideo = Label(window_fly,width=800,height=600,bg="yellow",image=imgtk)
    myvideo.place(x=90,y=10)
    
    pic_path = os.path.join(os.getcwd(), "systempic", "fly", "keyboard.png") #分析圖片按鈕
    pic = Image.open(pic_path)
    pic = pic.resize((int(pic.size[0]*keyboard_size), int(pic.size[1]*keyboard_size)))
    pic_tk = ImageTk.PhotoImage(image=pic)
    keyboard = Canvas(window_fly, bg="#E2F0D9", width=pic.size[0], height=pic.size[1], bd=0, highlightthickness=0, relief='ridge')
    keyboard.place(x=70,y=620)
    keyboard.create_image(0,0,anchor=tk.NW,image=pic_tk)
    
    pic1_path = os.path.join(os.getcwd(), "systempic", "fly", "connect_fly.png") #分析圖片按鈕
    pic1 = Image.open(pic1_path)
    pic1 = pic1.resize((int(pic1.size[0]*pic_size), int(pic1.size[1]*pic_size)))
    pic1_tk = ImageTk.PhotoImage(image=pic1)
    button_connect = Canvas(window_fly, bg="#E2F0D9", width=pic1.size[0], height=pic1.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_connect.bind("<Button-1>", lambda e: control())
    button_connect.create_image(0,0,anchor=tk.NW,image=pic1_tk)
    button_connect.place(x=670,y=630)
    
    pic2_path = os.path.join(os.getcwd(), "systempic", "fly", "screenshot.png") #分析圖片按鈕
    pic2 = Image.open(pic2_path)
    pic2 = pic2.resize((int(pic2.size[0]*pic_size), int(pic2.size[1]*pic_size)))
    pic2_tk = ImageTk.PhotoImage(image=pic2)
    button_catch = Canvas(window_fly, bg="#E2F0D9", width=pic2.size[0], height=pic2.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_catch.bind("<Button-1>", lambda e: cap_pic())
    button_catch.create_image(0,0,anchor=tk.NW,image=pic2_tk)
    button_catch.place(x=758,y=700)
    
    pic3_path = os.path.join(os.getcwd(), "systempic", "fly", "delete.png") #分析圖片按鈕
    pic3 = Image.open(pic3_path)
    pic3 = pic3.resize((int(pic3.size[0]*pic_size), int(pic3.size[1]*pic_size)))
    pic3_tk = ImageTk.PhotoImage(image=pic3)
    button_del = Canvas(window_fly, bg="#E2F0D9", width=pic3.size[0], height=pic3.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_del.bind("<Button-1>", lambda e: del_pic())
    button_del.create_image(0,0,anchor=tk.NW,image=pic3_tk)
    button_del.place(x=758,y=760)
    
    before_frame = tk.Frame(window_fly,width=532,height=400,bg="white") ####解析後圖片放的地方
    before_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    before_frame.place(x=1000,y=10)
    imgtkk = ImageTk.PhotoImage(file="output.png")
    before_pic=Label(before_frame,bg="yellow",text="截圖照片", font=("Courier", 12, "italic"),width=532,height=400,image=imgtkk)#解析後照片
    before_pic.pack()
    
    after_frame = tk.Frame(window_fly,width=532,height=400,bg="white") ####解析後圖片放的地方
    after_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    after_frame.place(x=1000,y=420)
    imgtkkk = ImageTk.PhotoImage(file="output.png")
    after_pic=Label(after_frame,bg="yellow",text="截圖照片", font=("Courier", 12, "italic"),width=532,height=400,image=imgtkkk)#解析後照片
    after_pic.pack()
    
    window_fly.mainloop()

def geo_window():
    root.destroy()
    window_geo = TkinterDnD.Tk()
    window_geo.title('分析圖片')
    
    w = window_geo.winfo_screenwidth()
    h = window_geo.winfo_screenheight()
    window_geo.geometry("%dx%d" %(w, h))
    window_geo.state("zoomed")
    window_geo.configure(bg='#E2F0D9') 
    
    pic_size=0.6
    
    img_path=[]
    def select_folder():
        select_folder = tk.Tk()
        select_folder.destroy()
        file_path = filedialog.askdirectory()
        folder_path_text.config(text=file_path)
        #將所有圖片加入list
        try:
            for img in os.listdir(file_path):
                imgpath=os.path.join(file_path,img)
                img_path.append(imgpath)
                mylist.insert(tk.END,img)
        except:
            pass
    pic1_path = os.path.join(os.getcwd(), "systempic", "geo", "select_folder.png") #分析圖片按鈕
    pic1 = Image.open(pic1_path)
    pic1 = pic1.resize((int(pic1.size[0]*pic_size), int(pic1.size[1]*pic_size)))
    pic1_tk = ImageTk.PhotoImage(image=pic1)
    button_select = Canvas(window_geo, bg="#E2F0D9", width=pic1.size[0], height=pic1.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_select.bind("<Button-1>", lambda e: select_folder())
    button_select.place(x=20,y=25)
    button_select.create_image(0,0,anchor=tk.NW,image=pic1_tk)
    
    pic2_path = os.path.join(os.getcwd(), "systempic", "geo", "folder_path.png") #分析圖片按鈕
    pic2 = Image.open(pic2_path)
    pic2 = pic2.resize((int(pic2.size[0]*pic_size), int(pic2.size[1]*pic_size)))
    pic2_tk = ImageTk.PhotoImage(image=pic2)
    folder_path = Canvas(window_geo, bg="#E2F0D9", width=pic2.size[0], height=pic2.size[1], bd=0, highlightthickness=0, relief='ridge')
    folder_path.place(x=285,y=30)
    folder_path.create_image(0,0,anchor=tk.NW,image=pic2_tk)
    
    folder_path_text = Label(window_geo,text="", font=("Courier", 18, "italic"), bg='white')
    folder_path_text.place(x=510,y=53)
    
    display_img_after_frame = tk.Frame(window_geo,width=600,height=400,bg="white") ####圖片放的地方
    display_img_after_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    display_img_after_frame.place(x=271,y=181)
    imgtk = ImageTk.PhotoImage(file="output.png")
    display_img_after=Label(display_img_after_frame,bg="yellow",text="解析後照片", font=("Courier", 12, "italic"),width=800,height=533,image=imgtk)#解析後照片
    display_img_after.pack()
    
    def onselect(event):
        def get_img():
            try:
                file_name=""
                for item in mylist.curselection():
                    file_name=str(img_path[item])
                display_pic = cv2.imread(file_name)
                display_pic = cv2.cvtColor(display_pic, cv2.COLOR_BGR2RGB)
                display_pic = cv2.resize(display_pic, (600, 450), interpolation=cv2.INTER_AREA)
                im = Image.fromarray(display_pic)
                imgtk2 = ImageTk.PhotoImage(image=im)
                display_img_after.config(image=imgtk2)
                display_img_after.image = imgtk2
            except:
                pass
        threading.Thread(target=get_img).start()
    out_list_frame = tk.Frame(window_geo,width=190,height=570,bg="yellow")
    list_frame = tk.Frame(out_list_frame,width=190,height=570,bg="green") #####圖片名稱列表
    list_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    mylist=tk.Listbox(list_frame,font=("Calibri",15),width=190,height=570)
    mylist.pack(side="left",fill="both",expand=1)
    scrollbar = tk.Scrollbar(out_list_frame)
    scrollbar.pack(side=tk.RIGHT, fill=tk.Y)
    scrollbar.config(command=mylist.yview)
    out_list_frame.place(x=35,y=141)
    list_frame.pack(expand=1, fill="both", side="left")
    mylist.bind('<<ListboxSelect>>', onselect)
    
    global google_map_url
    google_map_url=""
    def drop_file(event): #做超連結連結到google map
        def _get_if_exist(data, key):
            if key in data:
                return data[key]
            return None
        def _convert_to_degress(value):
            d = float(value.values[0].num) / float(value.values[0].den)
            m = float(value.values[1].num) / float(value.values[1].den)
            s = float(value.values[2].num) / float(value.values[2].den)
            return d + (m / 60.0) + (s / 3600.0)
        def get_exif_location(exif_data):
            lat = None
            lon = None
            gps_latitude = _get_if_exist(exif_data, 'GPS GPSLatitude')
            gps_latitude_ref = _get_if_exist(exif_data, 'GPS GPSLatitudeRef')
            gps_longitude = _get_if_exist(exif_data, 'GPS GPSLongitude')
            gps_longitude_ref = _get_if_exist(exif_data, 'GPS GPSLongitudeRef')
            if gps_latitude and gps_latitude_ref and gps_longitude and gps_longitude_ref:
                lat = _convert_to_degress(gps_latitude)
                if gps_latitude_ref.values[0] != 'N':
                    lat = 0 - lat
                lon = _convert_to_degress(gps_longitude)
                if gps_longitude_ref.values[0] != 'E':
                    lon = 0 - lon
            return lat, lon
        tags = exifread.process_file(open(event.data, 'rb'))
        geo = {i:tags[i] for i in tags.keys() if i.startswith('GPS')}
        lat,lon=get_exif_location(geo)
        api_key='AIzaSyDU0ez136Zk81khQv2Gx4N5_2ZI_lUism0'
        url = "https://maps.googleapis.com/maps/api/staticmap?key="+api_key+"&center="+str(lat)+","+str(lon)+"&zoom=20&maptype=satellite&size=640x640&format=jpg&markers=color:red%7Clabel:拍攝地點%7C"+str(lat)+","+str(lon)
        ret = requests.get(url).content
        im = Image.open(io.BytesIO(ret))
        imgtk2 = ImageTk.PhotoImage(image=im)
        mymap.config(image=imgtk2)
        mymap.image = imgtk2
        google_map_url="https://www.google.com/maps/search/?api=1&query="+str(lat)+" "+str(lon)+"&basemap=satellite"
    def google_map():
        def _get_if_exist(data, key):
            if key in data:
                return data[key]
            return None
        def _convert_to_degress(value):
            d = float(value.values[0].num) / float(value.values[0].den)
            m = float(value.values[1].num) / float(value.values[1].den)
            s = float(value.values[2].num) / float(value.values[2].den)
            return d + (m / 60.0) + (s / 3600.0)
        def get_exif_location(exif_data):
            lat = None
            lon = None
            gps_latitude = _get_if_exist(exif_data, 'GPS GPSLatitude')
            gps_latitude_ref = _get_if_exist(exif_data, 'GPS GPSLatitudeRef')
            gps_longitude = _get_if_exist(exif_data, 'GPS GPSLongitude')
            gps_longitude_ref = _get_if_exist(exif_data, 'GPS GPSLongitudeRef')
            if gps_latitude and gps_latitude_ref and gps_longitude and gps_longitude_ref:
                lat = _convert_to_degress(gps_latitude)
                if gps_latitude_ref.values[0] != 'N':
                    lat = 0 - lat
                lon = _convert_to_degress(gps_longitude)
                if gps_longitude_ref.values[0] != 'E':
                    lon = 0 - lon
            return lat, lon
        def get_google_map():
            file_name=""
            for item in mylist.curselection():
                file_name=str(img_path[item])
            tags = exifread.process_file(open(file_name, 'rb'))##
            geo = {i:tags[i] for i in tags.keys() if i.startswith('GPS')}
            lat,lon=get_exif_location(geo)
            api_key='AIzaSyDU0ez136Zk81khQv2Gx4N5_2ZI_lUism0'
            url = "https://maps.googleapis.com/maps/api/staticmap?key="+api_key+"&center="+str(lat)+","+str(lon)+"&zoom=20&maptype=satellite&size=640x640&format=jpg&markers=color:red%7Clabel:拍攝地點%7C"+str(lat)+","+str(lon)
            ret = requests.get(url).content
            im = Image.open(io.BytesIO(ret))
            imgtk2 = ImageTk.PhotoImage(image=im)
            mymap.config(image=imgtk2)
            mymap.image = imgtk2
            global google_map_url
            google_map_url="https://www.google.com/maps/search/?api=1&query="+str(lat)+" "+str(lon)+"&basemap=satellite"
        threading.Thread(target=get_google_map).start()
    def link_to_map(url):
        if (url==None):
            return
        webbrowser.open(url,new=2)
    pic4_path = os.path.join(os.getcwd(), "systempic", "analyze", "put_geo.png") #分析圖片按鈕
    pic4 = Image.open(pic4_path)
    pic4 = pic4.resize((int(pic4.size[0]*pic_size), int(pic4.size[1]*pic_size)))
    pic4_tk = ImageTk.PhotoImage(image=pic4)
    button_map = Canvas(window_geo, bg="#E2F0D9", width=pic4.size[0], height=pic4.size[1], bd=0, highlightthickness=0, relief='ridge', cursor="hand2")
    button_map.bind("<Button-1>", lambda e: google_map())
    button_map.create_image(0,0,anchor=tk.NW,image=pic4_tk)
    button_map.place(x=33,y=730)
    
    label_frame = tk.Frame(window_geo,width=640,height=640,bg="white") #####顯示Google map的地方
    label_frame.pack_propagate(0) # Stops child widgets of label_frame from resizing it
    mymap=tk.Label(label_frame,bg="yellow",fg="black",text="google map顯示處",font=("Calibri",15),width=640,height=640,cursor="hand2")
    mymap.pack()
    mymap.bind("<Button-1>", lambda e: link_to_map(google_map_url))
    mymap.drop_target_register(DND_FILES)
    mymap.dnd_bind('<<Drop>>', drop_file)
    label_frame.place(x=920,y=140)
    
    tree_path = os.path.join(os.getcwd(), "systempic", "geo", "tree.png") #分析圖片按鈕
    tree = Image.open(tree_path)
    tree = tree.resize((int(tree.size[0]*0.9), int(tree.size[1]*0.9)))
    tree_tk = ImageTk.PhotoImage(image=tree)
    tree_pic = Canvas(window_geo, bg="#E2F0D9", width=tree.size[0], height=tree.size[1], bd=0, highlightthickness=0, relief='ridge')
    tree_pic.place(x=275,y=613)
    tree_pic.create_image(0,0,anchor=tk.NW,image=tree_tk)
    
    def on_closing():
        window_geo.destroy()
        global root
        root=tk.Tk()
        root.withdraw()
        create_main_window()
    window_geo.protocol("WM_DELETE_WINDOW", on_closing)
    window_geo.mainloop()

global root
global fly_rcnn_model
global fly_cnn_model
root=tk.Tk()
root.withdraw()
create_main_window()









Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Instructions for updating:
box_ind is deprecated, use box_indices instead


Instructions for updating:
Use `tf.cast` instead.






Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Processing 1 images
image                    shape: (3648, 5472, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 384, 384, 3)      min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 5472.00000  float64
anchors                  shape: (1, 36828, 4)         min:   -1.41791  max:    2.25080  float32
[ 605 3660 1148 4116]
[ 686 1988 1119 2386]
[1241 1542 1690 1928]
[ 701 4223 1162 4712]
[ 660 1564 1163 1954]
[ 134 2961  608 3350]
[ 742 3058 1084 3401]
[1173 3083 1603 3475]
[1273  819 1744 1312]
[1125 4343 1602 4771]
[ 682 2486 1074 2883]
[1210 3785 1605 4263]
[ 172 1574  571 192

[2381 3909 3125 4593]
[2025 2851 2840 3850]
[2398 2208 3083 2888]
[1626 2285 2203 2876]
[ 178  107 1052 1103]
[2024 4515 2858 5403]
[1574 3774 2392 4567]
[1235 4523 2034 5399]
[ 461 4548 1259 5347]
[2744 2912 3578 3820]
Processing 1 images
image                    shape: (3648, 5472, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 384, 384, 3)      min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 14)               min:    0.00000  max: 5472.00000  float64
anchors                  shape: (1, 36828, 4)         min:   -1.41791  max:    2.25080  float32
[ 487  991 1304 1823]
[1280 1015 2167 1816]
[1839  549 2470 1075]
[ 917  434 1615 1065]
[1440 2747 2165 3628]
[  93  414  881 1057]
[2315  607 3299 1700]
[2606 3585 3514 4621]
[1415 2058 2031 2728]
Processing 1 images
image                    shape: (3648, 5472, 3)       min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 384, 384, 3)      min: -123.70

In [ ]:
def _get_if_exist(data, key):
    if key in data:
        return data[key]
    return None
def _convert_to_degress(value):
    d = float(value.values[0].num) / float(value.values[0].den)
    m = float(value.values[1].num) / float(value.values[1].den)
    s = float(value.values[2].num) / float(value.values[2].den)
    return d + (m / 60.0) + (s / 3600.0)
def get_exif_location(exif_data):
    lat = None
    lon = None
    gps_latitude = _get_if_exist(exif_data, 'GPS GPSLatitude')
    gps_latitude_ref = _get_if_exist(exif_data, 'GPS GPSLatitudeRef')
    gps_longitude = _get_if_exist(exif_data, 'GPS GPSLongitude')
    gps_longitude_ref = _get_if_exist(exif_data, 'GPS GPSLongitudeRef')
    if gps_latitude and gps_latitude_ref and gps_longitude and gps_longitude_ref:
        lat = _convert_to_degress(gps_latitude)
        if gps_latitude_ref.values[0] != 'N':
            lat = 0 - lat
        lon = _convert_to_degress(gps_longitude)
        if gps_longitude_ref.values[0] != 'E':
            lon = 0 - lon
    return lat, lon

tags = exifread.process_file(open(r'C:\Users\LAI\images\myimg.jpg', 'rb'))
geo = {i:tags[i] for i in tags.keys() if i.startswith('GPS')}
print(geo)
lat,lon=get_exif_location(geo)
lat=format(lat,'.6f')
lon=format(lon,'.6f')
print(str(lat)+" "+str(lon))

In [ ]:
#https://www.google.com/maps/search/?api=1&query=23.200073 120.254884&basemap=satellite

In [ ]:
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            im = Image.fromarray(gray)
            imgtk = PhotoImage(im)
            myvideo.config(image=imgtk)
            myvideo.image = imgtk

In [ ]:
        video = "udp://@0.0.0.0:11111"
        cap = cv2.VideoCapture(video)
        
        if not cap.isOpened():
            print("Cannot open camera")
        
        def test():
            while(True):
                ret, frame = cap.read()
                if not ret:
                    print("Can't receive frame (streamend?). Exiting ...")
                    break
                    
                rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                im = Image.fromarray(rgb)
                imgtk2 = ImageTk.PhotoImage(image=im)
                myvideo.config(image=imgtk2)
                myvideo.image = imgtk2
                    
            cap.release()
            cv2.destroyAllWindows()
            send('streamoff')
                    
        receiveThread = threading.Thread(target=test)  #接收無人機訊息用
        receiveThread.daemon = True
        receiveThread.start()

In [ ]:
root = TkinterDnD.Tk()  # notice - use this instead of tk.Tk()

lb = tk.Listbox(root)
lb.insert(1, "drag files to here")

# register the listbox as a drop target
lb.drop_target_register(DND_FILES)
lb.dnd_bind('<<Drop>>', lambda e: lb.insert(tk.END, e.data))

lb.pack()
root.mainloop()

In [ ]:
root = TkinterDnD.Tk()

label=Label(root,text="121313212313123121", font=("Courier", 12, "italic"))
label.drop_target_register(DND_FILES)
label.dnd_bind('<<Drop>>', lambda e: label.config(text=e.data))
label.pack()
root.mainloop()

In [ ]:
lat=23.200073
lon=120.254884
api_key='AIzaSyDU0ez136Zk81khQv2Gx4N5_2ZI_lUism0'
url = "https://maps.googleapis.com/maps/api/staticmap?key=" + api_key + "&center="+ str(lat) + "," + str(lon) + "&zoom=19&maptype=satellite&size=640x640&format=jpg&scale=2&markers=color:red%7Clabel:拍攝地點%7C"+str(lat)+","+str(lon)
ret = requests.get(url).content
image = Image.open(io.BytesIO(ret))
print(type(image))
image.show()

In [ ]:
    def drop_file(event):
        def _get_if_exist(data, key):
            if key in data:
                return data[key]
            return None
        def _convert_to_degress(value):
            d = float(value.values[0].num) / float(value.values[0].den)
            m = float(value.values[1].num) / float(value.values[1].den)
            s = float(value.values[2].num) / float(value.values[2].den)
            return d + (m / 60.0) + (s / 3600.0)
        def get_exif_location(exif_data):
            lat = None
            lon = None
            gps_latitude = _get_if_exist(exif_data, 'GPS GPSLatitude')
            gps_latitude_ref = _get_if_exist(exif_data, 'GPS GPSLatitudeRef')
            gps_longitude = _get_if_exist(exif_data, 'GPS GPSLongitude')
            gps_longitude_ref = _get_if_exist(exif_data, 'GPS GPSLongitudeRef')
            if gps_latitude and gps_latitude_ref and gps_longitude and gps_longitude_ref:
                lat = _convert_to_degress(gps_latitude)
                if gps_latitude_ref.values[0] != 'N':
                    lat = 0 - lat
                lon = _convert_to_degress(gps_longitude)
                if gps_longitude_ref.values[0] != 'E':
                    lon = 0 - lon
            return lat, lon
        def loadmap(event):
            drop_img_label.config(text=event.data)
            tags = exifread.process_file(open(event.data, 'rb'))
            geo = {i:tags[i] for i in tags.keys() if i.startswith('GPS')}
            lat,lon=get_exif_location(geo)
            for widget in label_frame.winfo_children():
                widget.destroy()
                widget.forget()
            mymap=tk.Label(label_frame,bg="yellow",fg="black",text="google map顯示處",font=("Calibri",15),width=700,height=650)
            mymap.pack()
            map_widget = tkintermapview.TkinterMapView(mymap, width=700, height=650, corner_radius=0)
            marker = map_widget.set_marker(lat,lon, text="拍攝地點")
            map_widget.set_position(lat, lon)
            map_widget.set_zoom(22)
            map_widget.set_tile_server("https://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}&s=Ga", max_zoom=23)
            map_widget.pack()
        threading.Thread(target=loadmap(event)).start()